#!/bin/bash

set -euo pipefail

echo "TEMPLATE DIR: $OUTPUT_DIR, ACTION: $ACTION, DRY_RUN: $DRY_RUN"

# Find all .yaml files that were not yet applied / deleted
find "$OUTPUT_DIR" \( -path "*/apply" -o -path "*/delete" \) -prune -o -type f -name "*.yaml" -print | while read -r TEMPLATE_FILE; do
   echo "kubectl $ACTION $TEMPLATE_FILE"

   if [[ "$DRY_RUN" == "false" ]]; then
     kubectl "$ACTION" -f "$TEMPLATE_FILE"
   fi

   BASE_DIR="$(dirname "$TEMPLATE_FILE")"
   FILENAME="$(basename "$TEMPLATE_FILE")"
   DEST_DIR="${BASE_DIR}/$ACTION"

   mkdir -p "$DEST_DIR"
   mv "$TEMPLATE_FILE" "$DEST_DIR/$FILENAME"
done

if [[ "$DRY_RUN" == "true" ]]; then
  exit 1
fi