#!/bin/bash

set -euo pipefail

SERVICE_DOMAIN=$(echo "$CONTEXT" | jq -r '.parameters.public_domain // .service.attributes.domain')

echo "Creating HTTPRoute for service $SERVICE_NAME with domain $SERVICE_DOMAIN"

echo "Creating public HTTPRoute..."

HTTPROUTE_FILE="$OUTPUT_DIR/httproute-$SERVICE_ID-public.yaml"
CONTEXT_PATH="$OUTPUT_DIR/context-$SERVICE_ID.json"

echo "$CONTEXT" > "$CONTEXT_PATH"

echo "Building Template: $TEMPLATE to $HTTPROUTE_FILE"

gomplate -c .="$CONTEXT_PATH" \
  --file "$TEMPLATE" \
  --out "$HTTPROUTE_FILE"

rm "$CONTEXT_PATH"