#!/bin/bash

set -eou pipefail

TOFU_VAR_FILE="$OUTPUT_DIR/terraform.tfvars.json"

echo "$TOFU_VARIABLES" > "$TOFU_VAR_FILE"

tofu -chdir="$TOFU_MODULE_DIR" init -input=false $TOFU_INIT_VARIABLES

tofu -chdir="$TOFU_MODULE_DIR" "$TOFU_ACTION" -auto-approve -var-file="$TOFU_VAR_FILE"

if [ "$TOFU_ACTION" = "apply" ]; then
  RESULTS=$(tofu -chdir="$TOFU_MODULE_DIR" output -json | jq 'map_values(.value)')

  np service action update --results "$RESULTS"
fi
